version: '3.8'

services:
  intro-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev" ]